### ISSUE TITLE
failed to find a checkpoint

### ISSUE THREAD

**Issue by angrybird-Z** [AliceAria/Performance-comparison-of-GAN-on-cifar-10#2]
Excuse me, I don't know if you're still here, but I already created a "checkpoint" folder when I ran this code. Why does it still show "Failed to find a checkpoint?"

**Comment by AliceAria** [comment]
Did you slove the problem? I have test my code just now and it worked well. Did you change the path for chekpoint?

**Comment by angrybird-Z** [comment]
Sorry, I missed your message.  I have solved this problem, but there are still some new problems. Do you mind if we communicate by email or wechat? my email: 751507950@qq.com my wechat DZ-751507950
